from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from PIL import Image
import os

def generate_pdf(name, age, gender, blood, label, confidence, info, input_image, heatmap_image):

    # File name
    file_path = "Skin_Disease_Report.pdf"

    # Create PDF
    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()
    content = []

    # ---------------- SAVE IMAGES TEMP ----------------
    input_path = "temp_input.jpg"
    heatmap_path = "temp_heatmap.jpg"

    # ---------------- FIX INPUT IMAGE ----------------
    if input_image.mode == "RGBA":
        input_image = input_image.convert("RGB")

    input_image.save(input_path)

    # ---------------- FIX HEATMAP ----------------
    heatmap_pil = Image.fromarray(heatmap_image)

    # Ensure heatmap is RGB
    if heatmap_pil.mode != "RGB":
        heatmap_pil = heatmap_pil.convert("RGB")

    heatmap_pil.save(heatmap_path)

    # ---------------- TITLE ----------------
    content.append(Paragraph("Skin In-Sight Diagnosis Report", styles["Title"]))
    content.append(Spacer(1, 15))

    # ---------------- PATIENT DETAILS ----------------
    content.append(Paragraph("<b>Patient Details</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph(f"Name: {name}", styles["Normal"]))
    content.append(Paragraph(f"Age: {age}", styles["Normal"]))
    content.append(Paragraph(f"Gender: {gender}", styles["Normal"]))
    content.append(Paragraph(f"Blood Group: {blood}", styles["Normal"]))

    content.append(Spacer(1, 15))

    # ---------------- INPUT IMAGE ----------------
    content.append(Paragraph("<b>Input Skin Image</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))
    content.append(RLImage(input_path, width=3*inch, height=3*inch))

    content.append(Spacer(1, 15))

    # ---------------- HEATMAP ----------------
    content.append(Paragraph("<b>Grad-CAM Heatmap</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))
    content.append(RLImage(heatmap_path, width=3*inch, height=3*inch))

    content.append(Spacer(1, 15))

    # ---------------- DIAGNOSIS ----------------
    content.append(Paragraph("<b>Diagnosis</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph(f"Disease Name: {label}", styles["Normal"]))
    content.append(Paragraph(f"Confidence Score: {confidence:.2f}", styles["Normal"]))

    content.append(Spacer(1, 15))

    # ---------------- DETAILS ----------------
    content.append(Paragraph("<b>Overview</b>", styles["Heading3"]))
    content.append(Paragraph(info["overview"], styles["Normal"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph("<b>Symptoms</b>", styles["Heading3"]))
    content.append(Paragraph(info["symptoms"], styles["Normal"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph("<b>Causes</b>", styles["Heading3"]))
    content.append(Paragraph(info["causes"], styles["Normal"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph("<b>Precautions & Medication</b>", styles["Heading3"]))
    content.append(Paragraph(info["precautions"], styles["Normal"]))

    content.append(Spacer(1, 20))

    # ---------------- FOOTER ----------------
    content.append(Paragraph("Generated by Skin In-Sight AI System", styles["Italic"]))

    # ---------------- BUILD PDF ----------------
    doc.build(content)

    # ---------------- CLEANUP TEMP FILES ----------------
    if os.path.exists(input_path):
        os.remove(input_path)
    if os.path.exists(heatmap_path):
        os.remove(heatmap_path)

    return file_path